#!/usr/bin/env bash
# Derive this worktree's isolated environment and write it to .env (gitignored).
#
# Every worktree gets its own compose project name and its own block of ports,
# derived deterministically from the worktree's absolute path -- so the values
# are stable across restarts but never collide between worktrees. The derivation
# itself lives in lib.sh because teardown needs it too, and teardown must not
# depend on a file a half-failed hook may have left truncated.
#
# What the ports are CALLED is the project's business: `AUTOFLEET_PORTS` in
# `.autofleet/config` names them, and each one lands here as `NAME=<port>`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
. ./scripts/fleet/lib.sh

fleet_derive_env "$REPO_ROOT" \
  || { echo "no sha1 tool (shasum/sha1sum/python3); cannot name this worktree's stack" >&2; exit 1; }

# `.autofleet/run/` WAS CREATED HERE and is not any more. It held the
# `reviewed-<sha>` push markers guard.py read and what the two local review
# passes wrote; armaatus/autofleet#152 removed both, so this made a directory
# nothing writes -- and the installer stopped adding it to the host's
# `.gitignore` in the same change, which left an untracked directory the payload
# creates and nothing ignores. Hard rule 1, in the direction the installer is
# supposed to guarantee. Found by the local /code-review pass.

# A private temp file per run, not a shared `.env.tmp`. Anything that reads .env
# may also GENERATE it when it is missing, so a second writer can be running at
# the same moment as this one. Sharing one temp path let the first `mv` carry
# off the second's source file, and the loser died on ENOENT -- which under
# `set -e` aborted provisioning at its first step and left a worktree with no
# rig at all (armaatus/rommsync-nx, where this came from).
FLEET_ENV_TMP="$(mktemp "$REPO_ROOT/.env.tmp.XXXXXX")"
trap 'rm -f "$FLEET_ENV_TMP"' EXIT

{
  echo "# Generated by scripts/fleet/env.sh -- do not commit, do not hand-edit."
  echo "# Regenerate with: ./scripts/fleet/env.sh"
  echo "COMPOSE_PROJECT_NAME=$fleet_project"
  echo "FLEET_PROJECT=$fleet_project"
  echo "FLEET_SLUG=$fleet_slug"
  # The offset, not just the ports derived from it: a project whose rig needs a
  # port autofleet was never told about can still derive one that cannot
  # collide, without inventing a second numbering scheme.
  echo "FLEET_OFFSET=$fleet_offset"
  fleet_ports
} > "$FLEET_ENV_TMP"

# Atomically, because a reader that sources .env unguarded may be polling from
# the moment the worktree exists, concurrently with this script. A read landing
# inside a truncating rewrite sees no COMPOSE_PROJECT_NAME, and compose then
# falls back to its own default: the wrong stack. Concurrent WRITERS are safe
# too -- the derivation is a pure function of the worktree path, so whichever
# rename lands last publishes byte-identical content.
mv -f "$FLEET_ENV_TMP" "$REPO_ROOT/.env"

echo "worktree env: project=$fleet_project offset=$fleet_offset"
fleet_ports | sed 's/^/  /'
