#!/usr/bin/env bash
# Derive this worktree's isolated environment and write it to .env (gitignored).
#
# Every worktree gets its own compose project, its own RomM port and its own
# proxy port, derived deterministically from the worktree's absolute path — so
# the values are stable across restarts but never collide between worktrees.
# See docs/TESTING.md and the Q8 decision in docs/DEVELOPMENT.md#worktree-isolation.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Stable, collision-resistant slug + port offset from the worktree path.
slug="$(basename "$REPO_ROOT" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')"
offset="$(python3 -c "
import hashlib,sys
h=hashlib.sha1(sys.argv[1].encode()).digest()
print(int.from_bytes(h[:2],'big') % 2000)
" "$REPO_ROOT")"

ROMM_PORT=$((21000 + offset))
PROXY_PORT=$((23000 + offset))
# The offset is part of the name, not just the ports: two worktrees whose
# leaf directory names collide (a checkout and a worktree both called
# "rommsync-nx") would otherwise share a compose project, and the second
# `up -d` would adopt and recreate the first's containers and database.
COMPOSE_PROJECT_NAME="rmx-${slug}-${offset}"

# Shared across worktrees on purpose: immutable, expensive to refetch. These are
# worktree-relative because Orca shares them via worktree.sharedDirectories in
# orca.yaml, which only accepts relative paths. Outside Orca they are ordinary
# local directories and everything still works, just without the sharing.
# Mutable state (RomM's database volume, build output) stays per-worktree.
ROM_CACHE="$REPO_ROOT/.cache/roms"
CCACHE_DIR="$REPO_ROOT/.cache/ccache"
mkdir -p "$ROM_CACHE" "$CCACHE_DIR"

cat > "$REPO_ROOT/.env" <<EOF
# Generated by scripts/orca/env.sh — do not commit, do not hand-edit.
# Regenerate with: ./scripts/orca/env.sh
COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
ROMM_PORT=$ROMM_PORT
PROXY_PORT=$PROXY_PORT
ROMM_BASE_URL=http://127.0.0.1:$ROMM_PORT
PROXY_BASE_URL=http://127.0.0.1:$PROXY_PORT
ROM_CACHE=$ROM_CACHE
CCACHE_DIR=$CCACHE_DIR
EOF

echo "worktree env: project=$COMPOSE_PROJECT_NAME romm=$ROMM_PORT proxy=$PROXY_PORT"
