#!/usr/bin/env bash
# Derive this worktree's isolated environment and write it to .env (gitignored).
#
# Every worktree gets its own compose project, its own RomM port and its own
# proxy port, derived deterministically from the worktree's absolute path — so
# the values are stable across restarts but never collide between worktrees.
# The derivation itself lives in lib.sh because teardown needs it too.
# See docs/TESTING.md and the Q8 decision in docs/DEVELOPMENT.md#worktree-isolation.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
. ./scripts/orca/lib.sh

orca_derive_env "$REPO_ROOT" \
  || { echo "no sha1 tool (shasum/sha1sum/python3); cannot name this worktree's stack" >&2; exit 1; }

# Shared across worktrees on purpose: immutable, expensive to refetch. These are
# worktree-relative because Orca shares them via worktree.sharedDirectories in
# orca.yaml, which only accepts relative paths. Outside Orca they are ordinary
# local directories and everything still works, just without the sharing.
# Mutable state (RomM's database volume, build output) stays per-worktree.
ROM_CACHE="$REPO_ROOT/.cache/roms"
CCACHE_DIR="$REPO_ROOT/.cache/ccache"
mkdir -p "$ROM_CACHE" "$CCACHE_DIR"

cat > "$REPO_ROOT/.env.tmp" <<EOF
# Generated by scripts/orca/env.sh — do not commit, do not hand-edit.
# Regenerate with: ./scripts/orca/env.sh
COMPOSE_PROJECT_NAME=$orca_project
ROMM_PORT=$orca_romm_port
PROXY_PORT=$orca_proxy_port
ROMM_BASE_URL=http://127.0.0.1:$orca_romm_port
PROXY_BASE_URL=http://127.0.0.1:$orca_proxy_port
ROM_CACHE=$ROM_CACHE
CCACHE_DIR=$CCACHE_DIR
EOF
# Atomically, because the romm tab polls `compose.sh` -- which sources .env
# unguarded -- from the moment the worktree exists, concurrently with this
# script. A read landing inside a truncating rewrite sees no
# COMPOSE_PROJECT_NAME, and docker-compose.yml then falls back to `rmx-local`:
# the wrong stack.
mv -f "$REPO_ROOT/.env.tmp" "$REPO_ROOT/.env"

echo "worktree env: project=$orca_project romm=$orca_romm_port proxy=$orca_proxy_port"
